#!/usr/bin/env bash

if [ "$SAGE_LOCAL" = "" ]; then
   echo "SAGE_LOCAL undefined ... exiting";
   echo "Maybe run 'sage -sh'?"
   exit 1
fi

# Remove old version
rm -fr "$SAGE_LOCAL"/lib/python/site-packages/manifolds*

# Apply patches. See SPKG.txt for information about what each patch
# does.

here=${PWD}

echo "Applying patches..."

# here we just simply copy the patched file
cp ${here}/patches/symbolic-patched/pynac.pyx ${SAGE_ROOT}/src/sage/symbolic
# building sage to check if everything is all right
${SAGE_ROOT}/sage -b

# Install new version

cd ${here}/src

echo "Building sage-manifolds..."

python setup.py install

if [ $? -ne 0 ]; then
   echo "Error installing manifolds."
   exit 1
fi

# Remove old documentation
rm -fr "$SAGE_ROOT"/src/doc/en/sagemanifolds*
cp -r doc/en/sagemanifolds "$SAGE_ROOT"/src/doc/en

exit 0
